---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: almalinux:8
    pre_build_image: true
    privileged: true
    command: /sbin/init
    env:
      USER: sy4may0
provisioner:
  name: ansible
verifier:
  name: ansible
